library(GRaNIE)
ATAC <- read.delim(sep = '\t', file = 'data/atac.pseudobulkFromClusters_cell_type_mean.tsv.gz')
RNAseq <- read.delim(sep = '\t', file = 'data/rna.pseudobulkFromClusters_cell_type_mean.tsv.gz')
metadata <- read.delim(sep = '\t', file = 'data/metadata_cell_type.tsv.gz')
metadata.l = list(name = "Leucocytes", data_peaks = 'ATAC',
                        data_rna = 'RNAseq', data_sampleMetadata = 'metadata', genomeAssembly = 'hg38')
GRN <- initializeGRN(objectMetadata = metadata.l, outputFolder = 'output_REAL', 'hg38')
grn <- addData(GRN, counts_peaks = ATAC, normalization_peaks = 'none', idColumn_peaks = 'peakID', counts_rna = RNAseq, normalization_rna = 'none', idColumn_RNA = 'ENSEMBL', sampleMetadata = metadata)
grn <- plotPCA_all(grn, forceRerun = TRUE)
grn <- addTFBS(grn, motifFolder = 'data/PWMScan_HOCOMOCOv12/H12INVIVO', translationTable = 'translationTable.csv', translationTable_sep = ' ', fileEnding = '.bed.gz', forceRerun = TRUE)
grn <- overlapPeaksAndTFBS(grn, nCores = 1)
grn <- addConnections_TF_peak(grn)
saveRDS(grn, 'grn_REAL_intermediary.rds')
grn <- readRDS('grn_REAL_intermediary.rds')
grn <- addConnections_peak_gene(grn, nCores = 1, forceRerun = TRUE)
grn <- filterGRNAndConnectGenes(grn, forceRerun = TRUE)
conections.all <- getGRNConnections(grn)
grn <- generateStatsSummary(grn, forceRerun = TRUE)
grn  <-  build_eGRN_graph(grn, forceRerun = TRUE)
grn <- visualizeGRN(grn, maxEdgesToPlot = 5300, forceRerun = TRUE)
saveRDS(grn, 'grn_REAL_semifinal.rds')
grn <- readRDS('grn_REAL_semifinal.rds')
